[global]
showWarningOnDirectExecution = false

[client]
showErrorDetails = false

[theme]

# Inherit from Streamlit's light base theme
base = "light"

# Elegant and modern accent color (teal green)
primaryColor = "#00796B"

# Clean, soft background
backgroundColor = "#FAFAFA"

# Subtle contrast for widgets
secondaryBackgroundColor = "#E0F2F1"

# Crisp, dark text
textColor = "#212121"

# Accent link color matching primary
linkColor = "#00796B"

# Gentle background for code blocks
codeBackgroundColor = "#F3F3F3"

# Classy, modern serif font
font = "serif"

# Monospace font for code (matches well with serif headers)
codeFont = "monospace"

# Slightly larger code size for readability
codeFontSize = "0.95rem"

# Use same elegant serif font for headings
headingFont = "serif"

# Light border tone for UI clarity
borderColor = "#DADADA"
dataframeBorderColor = "#DADADA"

# Clean look with subtle borders around widgets
showWidgetBorder = true

# Slightly larger font base
baseFontSize = 17

# Hide sidebar separator for a seamless look
showSidebarBorder = false

